### ISSUE TITLE
Data processing

### ISSUE THREAD

**Issue by lfxuan** [ginobilinie/medSynthesis#14]
I am very interested in your work, I now have some doubts：
(1)  In your paper, the image size  is 153X193X50, and The image size I used is 240X240X155, will the image size affect the result?
 (2)  In your paper, the MR size is 32X32X32, the CT size is 16X16X16, the image MR size obtained in the code is 64X64X64, the CT size is 48X48X48, but your note is THE MR size is 32X32X32, the CT size is 24X24X24, What dimension size should I take?

**Comment by ginobilinie** [comment]
1. The image size doesnot affect much. Donot worry about it.
2. In my later works, I begin to use 2D big patches, for example, 240*240*5 for input MRI, and 240*240*1 for output CT. Since this kind of pseudo 3D (actually 2D network) can be much faster for training and also easier to get converged, I encourage you to use such settings.
